version: "2"
services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: bitworks
    ports:
    - 5432:5432
  robot:
    image: allrad/check-robot:latest
    working_dir: /var/app
    command: [
      "mvn", "exec:java", "-Dexec.mainClass=bitworks.tz.App"
    ]
    volumes: 
    - ./config.ini:/var/app/config.ini